site_name: Compose Code Editor
site_description: 'Jetpack Compose Code Editor'
site_author: 'Waqas Tahir'
site_url: 'https://qawaz.github.io/compose-code-editor/'
remote_branch: gh-pages

docs_dir: docs

repo_name: 'compose-code-editor'
repo_url: 'https://github.com/qawaz/compose-code-editor'

theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'Overview': README.md
  - 'API' : api/codeeditor